apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-frontend-deployment
  labels:
    app: jobportal-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jobportal-frontend
  template:
    metadata:
      labels:
        app: jobportal-frontend
    spec:
      containers:
      - name: jobportal-frontend
        image: chausu/jobportal-frontend:2f04f262542aead7fd4d3124421fdf092b7ab662
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chmod -R 755 /usr/share/nginx/html/assets"]
