apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-backend-deployment
  namespace: jobportal
  labels:
    app: jobportal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobportal-backend
  template:
    metadata:
      labels:
        app: jobportal-backend
    spec:
      containers:
      - name: jobportal-backend
        image: chausu/jobportal-backend:d44525a3f44c9c01c94834a339962f09ece5e695
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: jobportal-backend-config
        - secretRef:
            name: jobportal-backend-secret
