apiVersion: v1
kind: Service
metadata:
  name: jobportal-backend-service
  namespace: jobportal
spec:
  type: ClusterIP
  selector:
    app: jobportal-backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
