apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jobportal
  name: jobportal-dev-role
rules:
  # Cấp quyền quản lý Workload (Pod, logs, Service, ConfigMap) trong namespace jobportal
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Cấp quyền quản trị Deployment Frontend & Backend
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobportal-dev-binding
  namespace: jobportal
subjects:
  - kind: User
    name: developer-jobportal
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: jobportal-dev-role
  apiGroup: rbac.authorization.k8s.io
