upstream jobportal_servers {
    server 192.168.233.112:30080;
    server 192.168.233.113:30080;
}

server {
    listen 80;
    server_name k8s-onpremise.chausu.name.vn api.chausu.name.vn;

    location / {
        proxy_pass http://jobportal_servers;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
